// Static enrichment layer — adds auth method, self-serve status, API surface,
// MCP availability, docs URL, and one-line description for all 100 apps.
// Sources: official developer docs, cross-checked July 2025.
// For apps not in Composio, this IS the research record.

export interface EnrichmentRecord {
  id: number;
  appName: string;
  oneLiner: string;
  authMethods: string[];       // e.g. ["OAuth2", "API Key"]
  selfServe: "Yes" | "No" | "Partial"; // can a dev get creds for free/trial?
  selfServeNote: string;       // brief evidence
  apiSurface: string;          // "REST", "GraphQL", "REST+GraphQL", "No public API", etc.
  apiBreath: "Narrow(<10)" | "Medium(10-50)" | "Wide(50+)" | "None";
  hasMCP: boolean;
  mcpNote: string;
  docsUrl: string;
  buildabilityBlocker: string; // "" = no blocker
}

export const enrichment: EnrichmentRecord[] = [
  // ── 1. CRM and Sales ──────────────────────────────────────────────────────
  {
    id: 1, appName: "Salesforce",
    oneLiner: "Industry-leading CRM for sales, service, and marketing automation.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free Developer Edition available at developer.salesforce.com",
    apiSurface: "REST+GraphQL+SOAP", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Salesforce MCP server (2025)",
    docsUrl: "https://developer.salesforce.com/docs/apis",
    buildabilityBlocker: "",
  },
  {
    id: 2, appName: "HubSpot",
    oneLiner: "CRM platform covering marketing, sales, and customer service.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free CRM account + developer sandbox at developers.hubspot.com",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official HubSpot MCP server announced 2025",
    docsUrl: "https://developers.hubspot.com/docs/api/overview",
    buildabilityBlocker: "",
  },
  {
    id: 3, appName: "Pipedrive",
    oneLiner: "Sales-focused CRM built around pipeline visualization.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial, API key in settings, dev OAuth via Marketplace",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.pipedrive.com/docs/api/v1",
    buildabilityBlocker: "",
  },
  {
    id: 4, appName: "Attio",
    oneLiner: "Modern data-driven CRM with flexible objects and workflows.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API token in workspace settings",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Attio MCP server available",
    docsUrl: "https://docs.attio.com/docs/overview",
    buildabilityBlocker: "",
  },
  {
    id: 5, appName: "Twenty",
    oneLiner: "Open-source CRM, self-hostable alternative to Salesforce.",
    authMethods: ["API Key", "OAuth2"], selfServe: "Yes",
    selfServeNote: "MIT-licensed OSS; free cloud or self-host; API key in settings",
    apiSurface: "REST+GraphQL", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Community MCP server exists on GitHub",
    docsUrl: "https://developers.twenty.com",
    buildabilityBlocker: "Not yet in Composio toolkit registry",
  },
  {
    id: 6, appName: "Podio",
    oneLiner: "Flexible work-management and CRM platform by Citrix.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free tier available; developer app registration at podio.com/developers",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.podio.com",
    buildabilityBlocker: "Not in Composio; needs new toolkit",
  },
  {
    id: 7, appName: "Zoho CRM",
    oneLiner: "Full-featured CRM from Zoho's broad business-software suite.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free tier for up to 3 users; OAuth via Zoho API Console",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Zoho published official MCP server 2025",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v6/",
    buildabilityBlocker: "",
  },
  {
    id: 8, appName: "Close",
    oneLiner: "Sales CRM focused on outbound calling and pipeline for SMBs.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; API key in Settings > API Keys",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.close.com",
    buildabilityBlocker: "Only 6 tools in Composio — limited surface",
  },
  {
    id: 9, appName: "Copper",
    oneLiner: "CRM deeply integrated with Google Workspace for Gmail-native workflows.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; API key in account settings",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.copper.com",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 10, appName: "DealCloud",
    oneLiner: "Enterprise deal-management and CRM platform for financial services firms.",
    authMethods: ["OAuth2", "API Key"], selfServe: "No",
    selfServeNote: "Enterprise sales-gated; no free tier or public dev sandbox",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Intapp MCP server announced 2025 for DealCloud data",
    docsUrl: "https://api.docs.dealcloud.com",
    buildabilityBlocker: "Enterprise-gated access; not in Composio",
  },

  // ── 2. Support and Helpdesk ───────────────────────────────────────────────
  {
    id: 11, appName: "Zendesk",
    oneLiner: "Market-leading customer support and ticketing platform.",
    authMethods: ["OAuth2", "API Key", "Basic Auth"], selfServe: "Yes",
    selfServeNote: "Free trial available; API token in Admin > API settings",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Zendesk MCP server available",
    docsUrl: "https://developer.zendesk.com/api-reference/",
    buildabilityBlocker: "",
  },
  {
    id: 12, appName: "Intercom",
    oneLiner: "Customer messaging platform for support, sales, and onboarding.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; access tokens in Developer Hub",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Intercom MCP server published 2025",
    docsUrl: "https://developers.intercom.com/docs",
    buildabilityBlocker: "",
  },
  {
    id: 13, appName: "Freshdesk",
    oneLiner: "Cloud-based helpdesk with ticketing, automation, and self-service portals.",
    authMethods: ["API Key", "Basic Auth"], selfServe: "Yes",
    selfServeNote: "Free Sprout plan available; API key in Profile settings",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.freshdesk.com/api/",
    buildabilityBlocker: "",
  },
  {
    id: 14, appName: "Front",
    oneLiner: "Collaborative inbox and customer communication platform for teams.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free trial available; API token in Settings > API & Webhooks",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://dev.frontapp.com/docs",
    buildabilityBlocker: "0 tools exposed in Composio despite toolkit existing",
  },
  {
    id: 15, appName: "Pylon",
    oneLiner: "B2B customer support platform focused on Slack-native support.",
    authMethods: ["Bearer Token"], selfServe: "Yes",
    selfServeNote: "API tokens available to admins in Pylon settings",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.usepylon.com/pylon-docs/developer",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 16, appName: "LiveAgent",
    oneLiner: "All-in-one help desk with live chat, ticketing, and call center.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "30-day free trial; API key in Configuration > API",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://www.ladesk.com/features/api/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 17, appName: "Plain",
    oneLiner: "Developer-first customer support platform with GraphQL API.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free tier available; API key in Settings > API keys",
    apiSurface: "GraphQL", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://www.plain.com/docs",
    buildabilityBlocker: "",
  },
  {
    id: 18, appName: "Help Scout",
    oneLiner: "Customer support platform with shared inbox and knowledge base.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free trial; OAuth app registration at developer.helpscout.com",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.helpscout.com/docs-api/",
    buildabilityBlocker: "",
  },
  {
    id: 19, appName: "Gorgias",
    oneLiner: "E-commerce helpdesk deeply integrated with Shopify, WooCommerce.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Trial available; API access via Settings > REST API",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.gorgias.com",
    buildabilityBlocker: "",
  },
  {
    id: 20, appName: "Gladly",
    oneLiner: "People-centered enterprise customer service platform.",
    authMethods: ["API Key", "OAuth2"], selfServe: "No",
    selfServeNote: "Enterprise-only; no public self-serve trial or free tier",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.gladly.com",
    buildabilityBlocker: "Enterprise sales-gated; not in Composio",
  },

  // ── 3. Communications and Messaging ──────────────────────────────────────
  {
    id: 21, appName: "Slack",
    oneLiner: "Team messaging and collaboration hub with deep app ecosystem.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free workspace; create Slack app at api.slack.com for OAuth",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://api.slack.com/docs",
    buildabilityBlocker: "",
  },
  {
    id: 22, appName: "Twilio",
    oneLiner: "Cloud communications platform for SMS, voice, video, and email.",
    authMethods: ["API Key", "Basic Auth"], selfServe: "Yes",
    selfServeNote: "Free trial with $15 credit; Account SID + Auth Token from console",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Twilio MCP server published 2025",
    docsUrl: "https://www.twilio.com/docs/usage/api",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 23, appName: "Zoho Cliq",
    oneLiner: "Team messaging and video conferencing tool within Zoho ecosystem.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free tier available; OAuth via Zoho API Console",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://cliq.zoho.com/developer/platform",
    buildabilityBlocker: "Not in Composio; Zoho toolkit covers Zoho CRM only",
  },
  {
    id: 24, appName: "Lark (Larksuite)",
    oneLiner: "All-in-one enterprise collaboration suite (messaging, docs, calendar) by ByteDance.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan; developer access at open.larksuite.com",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Lark/Feishu MCP server available on GitHub",
    docsUrl: "https://open.larksuite.com/document/home/index",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 25, appName: "Pumble",
    oneLiner: "Free team communication app — Slack alternative for cost-conscious teams.",
    authMethods: ["API Key", "OAuth2"], selfServe: "Yes",
    selfServeNote: "Free plan; API access via workspace settings",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://api.pumble.com",
    buildabilityBlocker: "Not in Composio; limited public API surface",
  },
  {
    id: 26, appName: "Discord",
    oneLiner: "Voice, video, and text community platform originally for gaming.",
    authMethods: ["OAuth2", "Bot Token"], selfServe: "Yes",
    selfServeNote: "Free; create app at discord.com/developers/applications",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://discord.com/developers/docs/intro",
    buildabilityBlocker: "",
  },
  {
    id: 27, appName: "Telegram",
    oneLiner: "Encrypted messaging app with powerful bot and channel APIs.",
    authMethods: ["Bot Token"], selfServe: "Yes",
    selfServeNote: "Free; create bot via @BotFather to get token instantly",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://core.telegram.org/bots/api",
    buildabilityBlocker: "",
  },
  {
    id: 28, appName: "WhatsApp Business",
    oneLiner: "Meta's business messaging API for customer communication at scale.",
    authMethods: ["OAuth2", "Bearer Token"], selfServe: "Partial",
    selfServeNote: "Cloud API free to test via Meta developers; send limits until verified",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.facebook.com/docs/whatsapp/cloud-api",
    buildabilityBlocker: "",
  },
  {
    id: 29, appName: "Aircall",
    oneLiner: "Cloud-based business phone system and call center software.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "7-day free trial; API credentials in Aircall Dashboard",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.aircall.io/api-references/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 30, appName: "Vonage",
    oneLiner: "Communications APIs for SMS, voice, video, and verification (now Ericsson).",
    authMethods: ["API Key", "JWT"], selfServe: "Yes",
    selfServeNote: "Free trial with €2 credit; API key from developer dashboard",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.vonage.com/en/documentation",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },

  // ── 4. Marketing, Ads, Email and Social ──────────────────────────────────
  {
    id: 31, appName: "Google Ads",
    oneLiner: "Google's advertising platform for search, display, and video ads.",
    authMethods: ["OAuth2"], selfServe: "Partial",
    selfServeNote: "OAuth free; API access needs developer token approval (standard access gated)",
    apiSurface: "REST+gRPC", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.google.com/google-ads/api/docs/start",
    buildabilityBlocker: "",
  },
  {
    id: 32, appName: "Meta Ads",
    oneLiner: "Facebook/Instagram ad management and analytics APIs.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free; create Meta app at developers.facebook.com for access token",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.facebook.com/docs/marketing-apis",
    buildabilityBlocker: "",
  },
  {
    id: 33, appName: "LinkedIn Ads",
    oneLiner: "LinkedIn's marketing and advertising API for B2B campaigns.",
    authMethods: ["OAuth2"], selfServe: "Partial",
    selfServeNote: "OAuth free; Marketing Developer Platform requires application review",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://learn.microsoft.com/en-us/linkedin/marketing/",
    buildabilityBlocker: "",
  },
  {
    id: 34, appName: "GoHighLevel",
    oneLiner: "All-in-one marketing and CRM platform for agencies.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; API key in Settings > API Keys",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://highlevel.stoplight.io/docs/integrations",
    buildabilityBlocker: "",
  },
  {
    id: 35, appName: "Mailchimp",
    oneLiner: "Email marketing platform with automation, landing pages, and analytics.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan for up to 500 contacts; API key in Account > Extras",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://mailchimp.com/developer/marketing/api/",
    buildabilityBlocker: "",
  },
  {
    id: 36, appName: "Klaviyo",
    oneLiner: "Email and SMS marketing automation platform focused on e-commerce.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan up to 250 contacts; API key in Account > Settings > API Keys",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.klaviyo.com/en",
    buildabilityBlocker: "",
  },
  {
    id: 37, appName: "systeme.io",
    oneLiner: "All-in-one funnel builder, email marketing, and online course platform.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API key in Profile > API",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.systeme.io",
    buildabilityBlocker: "Not in Composio; very limited API surface",
  },
  {
    id: 38, appName: "Pinterest",
    oneLiner: "Visual discovery and social media platform with ad and content APIs.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Register app at developers.pinterest.com; standard access free",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.pinterest.com/docs/getting-started/introduction/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 39, appName: "Threads (Meta)",
    oneLiner: "Meta's text-based social platform (Twitter/X alternative).",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Threads API public since mid-2024; app at developers.facebook.com",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.facebook.com/docs/threads",
    buildabilityBlocker: "Not in Composio; API still limited (post, reply, insights only)",
  },
  {
    id: 40, appName: "SendGrid",
    oneLiner: "Transactional and marketing email delivery service by Twilio.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free plan with 100 emails/day; API key from Settings > API Keys",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.sendgrid.com/api-reference/",
    buildabilityBlocker: "",
  },

  // ── 5. Ecommerce ─────────────────────────────────────────────────────────
  {
    id: 41, appName: "Shopify",
    oneLiner: "Leading e-commerce platform for building and managing online stores.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free dev store via Partners program; public or custom app credentials",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Shopify MCP server available via Shopify Dev",
    docsUrl: "https://shopify.dev/docs/api",
    buildabilityBlocker: "",
  },
  {
    id: 42, appName: "WooCommerce",
    oneLiner: "Open-source WordPress e-commerce plugin powering millions of stores.",
    authMethods: ["API Key", "OAuth1"], selfServe: "Yes",
    selfServeNote: "Free plugin; API keys generated in WooCommerce > Settings > Advanced > REST API",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    buildabilityBlocker: "Not in Composio; self-hosted so instance URL required per store",
  },
  {
    id: 43, appName: "BigCommerce",
    oneLiner: "SaaS e-commerce platform for mid-market and enterprise merchants.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free trial + sandbox; API credentials in Advanced Settings > API Accounts",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.bigcommerce.com/docs/rest-management",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 44, appName: "Salesforce Commerce Cloud",
    oneLiner: "Enterprise e-commerce platform (formerly Demandware) by Salesforce.",
    authMethods: ["OAuth2"], selfServe: "No",
    selfServeNote: "Enterprise contracts required; sandbox needs Salesforce partnership",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.salesforce.com/docs/commerce/commerce-api",
    buildabilityBlocker: "Enterprise/partner-gated; not in Composio",
  },
  {
    id: 45, appName: "Magento (Adobe Commerce)",
    oneLiner: "Open-source and enterprise e-commerce platform by Adobe.",
    authMethods: ["OAuth2", "API Key", "Bearer Token"], selfServe: "Yes",
    selfServeNote: "Magento Open Source free; Adobe Commerce enterprise requires license",
    apiSurface: "REST+GraphQL+SOAP", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.adobe.com/commerce/webapi/",
    buildabilityBlocker: "Not in Composio; self-hosted so instance-specific",
  },
  {
    id: 46, appName: "Squarespace",
    oneLiner: "Website builder and e-commerce platform for creatives.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day trial; developer platform at developers.squarespace.com",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.squarespace.com/commerce-apis/introduction",
    buildabilityBlocker: "Not in Composio; limited API surface (orders/inventory focus)",
  },
  {
    id: 47, appName: "Ecwid",
    oneLiner: "Embeddable e-commerce store widget and platform by Lightspeed.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API access at my.ecwid.com/apps",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://api-docs.ecwid.com",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 48, appName: "Gumroad",
    oneLiner: "Simple platform for creators to sell digital products directly.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free account; OAuth app registration at gumroad.com/api",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://app.gumroad.com/api",
    buildabilityBlocker: "Only 7 tools; narrow surface",
  },
  {
    id: 49, appName: "Amazon Selling Partner",
    oneLiner: "Amazon's API for third-party sellers to manage listings, orders, and inventory.",
    authMethods: ["OAuth2"], selfServe: "Partial",
    selfServeNote: "Free to register as developer; listing on Marketplace or self-authorization needed",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer-docs.amazon.com/sp-api/docs",
    buildabilityBlocker: "0 tools exposed in Composio despite toolkit existing",
  },
  {
    id: 50, appName: "fanbasis",
    oneLiner: "Fan engagement and monetization platform for sports and entertainment.",
    authMethods: ["API Key"], selfServe: "No",
    selfServeNote: "No public developer docs; contact-sales required",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://fanbasis.com",
    buildabilityBlocker: "No public API docs; partner-gated; not in Composio",
  },

  // ── 6. Data, SEO and Scraping ─────────────────────────────────────────────
  {
    id: 51, appName: "DataForSEO",
    oneLiner: "SEO data APIs for SERP, keyword, backlink, and content analysis.",
    authMethods: ["Basic Auth"], selfServe: "Yes",
    selfServeNote: "Pay-as-you-go; register at dataforseo.com, get credentials instantly",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official DataForSEO MCP server available",
    docsUrl: "https://docs.dataforseo.com",
    buildabilityBlocker: "",
  },
  {
    id: 52, appName: "SE Ranking",
    oneLiner: "All-in-one SEO platform with rank tracking, site audit, and backlinks.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; API token in Account Settings",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://seranking.com/api.html",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 53, appName: "Ahrefs",
    oneLiner: "SEO toolset for backlink analysis, keyword research, and site audits.",
    authMethods: ["API Key"], selfServe: "Partial",
    selfServeNote: "API access requires paid Ahrefs subscription (starts $99/mo)",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Community MCP server available for Ahrefs",
    docsUrl: "https://docs.ahrefs.com/docs/api/v3",
    buildabilityBlocker: "",
  },
  {
    id: 54, appName: "MrScraper",
    oneLiner: "AI-powered web scraping tool with natural language selectors.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API key from dashboard",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.mrscraper.com",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 55, appName: "Apify",
    oneLiner: "Web scraping and automation platform with 1,500+ pre-built actors.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free $5/month credits; API token in Settings > Integrations",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Apify MCP server (apify-mcp) in Composio registry",
    docsUrl: "https://docs.apify.com/api/v2",
    buildabilityBlocker: "",
  },
  {
    id: 56, appName: "Firecrawl",
    oneLiner: "Developer-first web scraping and crawling API with markdown output.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free 500 credits/month; API key from firecrawl.dev dashboard",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: true, mcpNote: "Official Firecrawl MCP server available",
    docsUrl: "https://docs.firecrawl.dev",
    buildabilityBlocker: "",
  },
  {
    id: 57, appName: "Bright Data",
    oneLiner: "Enterprise proxy network and web data collection infrastructure.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free trial with credit; API token from Bright Data console",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: true, mcpNote: "Official Bright Data MCP server available",
    docsUrl: "https://docs.brightdata.com",
    buildabilityBlocker: "",
  },
  {
    id: 58, appName: "Sherlock",
    oneLiner: "Open-source CLI tool to find social media accounts by username.",
    authMethods: ["None"], selfServe: "Yes",
    selfServeNote: "MIT-licensed OSS CLI; no API — runs locally via Python",
    apiSurface: "No public API", apiBreath: "None",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://github.com/sherlock-project/sherlock",
    buildabilityBlocker: "CLI tool, no REST API; would need wrapper to build agent toolkit",
  },
  {
    id: 59, appName: "Waterfall.io",
    oneLiner: "B2B contact enrichment waterfall — chains multiple data providers.",
    authMethods: ["API Key"], selfServe: "No",
    selfServeNote: "No public self-serve signup; contact sales required",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://waterfall.io",
    buildabilityBlocker: "Sales-gated access; no public docs; not in Composio",
  },
  {
    id: 60, appName: "Clay",
    oneLiner: "Data enrichment and GTM automation platform for revenue teams.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API access for integrations in Settings",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://www.clay.com/docs",
    buildabilityBlocker: "Not in Composio; API focused on import/webhooks, limited outbound",
  },

  // ── 7. Developer, Infra and Data Platforms ───────────────────────────────
  {
    id: 61, appName: "GitHub",
    oneLiner: "World's largest code hosting and collaboration platform.",
    authMethods: ["OAuth2", "PAT", "GitHub App"], selfServe: "Yes",
    selfServeNote: "Free account; PAT in Settings > Developer Settings instantly",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official GitHub MCP server (github.com/github/github-mcp-server)",
    docsUrl: "https://docs.github.com/en/rest",
    buildabilityBlocker: "",
  },
  {
    id: 62, appName: "Vercel",
    oneLiner: "Frontend cloud platform for deploying and scaling web applications.",
    authMethods: ["API Key", "OAuth2"], selfServe: "Yes",
    selfServeNote: "Free Hobby plan; API token in Settings > Tokens",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Vercel MCP server available",
    docsUrl: "https://vercel.com/docs/rest-api",
    buildabilityBlocker: "",
  },
  {
    id: 63, appName: "Netlify",
    oneLiner: "JAMstack hosting and CI/CD platform for modern web projects.",
    authMethods: ["OAuth2", "PAT"], selfServe: "Yes",
    selfServeNote: "Free tier; PAT in User Settings > Applications",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.netlify.com/api/get-started/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 64, appName: "Cloudflare",
    oneLiner: "Global CDN, DNS, security, and edge computing platform.",
    authMethods: ["API Key", "API Token", "OAuth2"], selfServe: "Yes",
    selfServeNote: "Free plan; API token in My Profile > API Tokens",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Cloudflare MCP server available",
    docsUrl: "https://developers.cloudflare.com/api/",
    buildabilityBlocker: "",
  },
  {
    id: 65, appName: "Supabase",
    oneLiner: "Open-source Firebase alternative: Postgres, Auth, Storage, Edge Functions.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free tier; API key in Project Settings > API",
    apiSurface: "REST+GraphQL", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Supabase MCP server available",
    docsUrl: "https://supabase.com/docs/reference/javascript/introduction",
    buildabilityBlocker: "",
  },
  {
    id: 66, appName: "Neo4j",
    oneLiner: "Leading graph database for connected data and relationship queries.",
    authMethods: ["OAuth2", "API Key", "Basic Auth"], selfServe: "Yes",
    selfServeNote: "Free AuraDB free tier; API credentials from AuraDB console",
    apiSurface: "REST+Bolt", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Neo4j MCP server available",
    docsUrl: "https://neo4j.com/docs/http-api/current/",
    buildabilityBlocker: "",
  },
  {
    id: 67, appName: "Snowflake",
    oneLiner: "Cloud data warehouse for analytics, data sharing, and ML workloads.",
    authMethods: ["OAuth2", "Key Pair", "Password"], selfServe: "Yes",
    selfServeNote: "30-day free trial; OAuth via Snowflake partner connector setup",
    apiSurface: "REST+SQL", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Snowflake MCP server available",
    docsUrl: "https://docs.snowflake.com/en/developer-guide/sql-api/index",
    buildabilityBlocker: "",
  },
  {
    id: 68, appName: "MongoDB Atlas",
    oneLiner: "Managed MongoDB cloud database with Data API and Atlas Search.",
    authMethods: ["API Key", "Bearer Token"], selfServe: "Yes",
    selfServeNote: "Free M0 cluster; API key in Organization > Access Manager",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official MongoDB MCP server available",
    docsUrl: "https://www.mongodb.com/docs/atlas/api/atlas-admin-api-ref/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 69, appName: "Datadog",
    oneLiner: "Cloud monitoring and observability platform for infrastructure and APM.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "14-day free trial; API key in Organization Settings > API Keys",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Datadog MCP server available",
    docsUrl: "https://docs.datadoghq.com/api/latest/",
    buildabilityBlocker: "",
  },
  {
    id: 70, appName: "Sentry",
    oneLiner: "Application error monitoring and performance tracking platform.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free developer plan; Auth Token in User Settings > Auth Tokens",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Sentry MCP server available",
    docsUrl: "https://docs.sentry.io/api/",
    buildabilityBlocker: "",
  },

  // ── 8. Productivity and Project Management ───────────────────────────────
  {
    id: 71, appName: "Notion",
    oneLiner: "All-in-one workspace for notes, docs, databases, and project management.",
    authMethods: ["OAuth2", "Integration Token"], selfServe: "Yes",
    selfServeNote: "Free plan; integration token in Settings & Members > Integrations",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Notion MCP server available",
    docsUrl: "https://developers.notion.com/docs/getting-started",
    buildabilityBlocker: "",
  },
  {
    id: 72, appName: "Airtable",
    oneLiner: "Spreadsheet-database hybrid for structured data and workflow automation.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan; API key in Account overview",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Airtable MCP server available",
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    buildabilityBlocker: "",
  },
  {
    id: 73, appName: "Linear",
    oneLiner: "Streamlined issue tracker and project management tool for software teams.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan for small teams; API key in Settings > API",
    apiSurface: "GraphQL", apiBreath: "Medium(10-50)",
    hasMCP: true, mcpNote: "Official Linear MCP server available",
    docsUrl: "https://developers.linear.app/docs",
    buildabilityBlocker: "",
  },
  {
    id: 74, appName: "Jira",
    oneLiner: "Atlassian's industry-standard project tracking and agile tool.",
    authMethods: ["OAuth2", "API Token", "Basic Auth"], selfServe: "Yes",
    selfServeNote: "Free plan up to 10 users; API token in Atlassian account settings",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Atlassian MCP server (Jira + Confluence) available",
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    buildabilityBlocker: "",
  },
  {
    id: 75, appName: "Asana",
    oneLiner: "Work management platform for task tracking, projects, and team goals.",
    authMethods: ["OAuth2", "PAT"], selfServe: "Yes",
    selfServeNote: "Free plan; PAT in My Profile Settings > Apps > Manage Developer Apps",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.asana.com/docs",
    buildabilityBlocker: "",
  },
  {
    id: 76, appName: "Monday.com",
    oneLiner: "Visual work OS for project management, CRM, and cross-team workflows.",
    authMethods: ["OAuth2", "API Token"], selfServe: "Yes",
    selfServeNote: "Free plan for 2 seats; API token in Profile > Administration > API",
    apiSurface: "GraphQL", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Monday.com MCP server available",
    docsUrl: "https://developer.monday.com/apps/docs",
    buildabilityBlocker: "",
  },
  {
    id: 77, appName: "ClickUp",
    oneLiner: "All-in-one productivity platform for tasks, docs, goals, and chat.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan; API key in Settings > Apps",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://clickup.com/api/clickupreference/operation/GetAuthorizedTeams/",
    buildabilityBlocker: "",
  },
  {
    id: 78, appName: "Coda",
    oneLiner: "Collaborative doc platform blending spreadsheets, databases, and apps.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free plan; API token at coda.io/account",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://coda.io/developers/apis/v1",
    buildabilityBlocker: "",
  },
  {
    id: 79, appName: "Smartsheet",
    oneLiner: "Spreadsheet-style project and work management platform.",
    authMethods: ["OAuth2", "API Token"], selfServe: "Yes",
    selfServeNote: "Free trial; API access token in Account > Personal Settings > API Access",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://smartsheet.redoc.ly/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 80, appName: "Harvest",
    oneLiner: "Time-tracking and invoicing tool for freelancers and teams.",
    authMethods: ["OAuth2", "PAT"], selfServe: "Yes",
    selfServeNote: "Free plan for 1 seat; PAT via Developer Portal at id.getharvest.com",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://help.getharvest.com/api-v2/",
    buildabilityBlocker: "",
  },

  // ── 9. Finance and Fintech ────────────────────────────────────────────────
  {
    id: 81, appName: "Stripe",
    oneLiner: "Developer-first payments platform for online and in-person commerce.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free account; test API keys available immediately in Dashboard",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: true, mcpNote: "Official Stripe MCP server available",
    docsUrl: "https://stripe.com/docs/api",
    buildabilityBlocker: "",
  },
  {
    id: 82, appName: "Plaid",
    oneLiner: "Financial data network connecting apps to bank accounts and transactions.",
    authMethods: ["API Key"], selfServe: "Partial",
    selfServeNote: "Sandbox free; Production access requires application review (2–4 weeks)",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://plaid.com/docs/",
    buildabilityBlocker: "Production gated by Plaid review; not in Composio",
  },
  {
    id: 83, appName: "Binance",
    oneLiner: "World's largest cryptocurrency exchange with trading and data APIs.",
    authMethods: ["API Key", "HMAC"], selfServe: "Yes",
    selfServeNote: "Free account; API key from User Center > API Management",
    apiSurface: "REST+WebSocket", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://binance-docs.github.io/apidocs/spot/en/",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 84, appName: "Paygent Connect",
    oneLiner: "Japanese payment gateway (NMI-powered) for card processing and subscriptions.",
    authMethods: ["API Key"], selfServe: "No",
    selfServeNote: "No public self-serve; merchant account application required",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://paygent.co.jp/merchant/develop/tech_info/",
    buildabilityBlocker: "Merchant-gated; Japanese-market only; not in Composio",
  },
  {
    id: 85, appName: "iPayX",
    oneLiner: "AI-powered payment processing and financial services API platform.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Sandbox available at ipayx.ai; API key from developer portal",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://ipayx.ai/docs",
    buildabilityBlocker: "Very new/niche; not in Composio",
  },
  {
    id: 86, appName: "QuickBooks",
    oneLiner: "Leading small-business accounting and finance software by Intuit.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Sandbox free at developer.intuit.com; OAuth via Intuit Developer",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/account",
    buildabilityBlocker: "",
  },
  {
    id: 87, appName: "Xero",
    oneLiner: "Cloud accounting software for small businesses with 1000+ integrations.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Demo company free; OAuth app at developer.xero.com",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.xero.com/documentation/api/accounting/overview",
    buildabilityBlocker: "",
  },
  {
    id: 88, appName: "Brex",
    oneLiner: "Corporate cards and spend management platform for startups and enterprises.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Partial",
    selfServeNote: "Brex account required (free to open); OAuth via developer.brex.com",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developer.brex.com/openapi/transactions_api/",
    buildabilityBlocker: "",
  },
  {
    id: 89, appName: "Ramp",
    oneLiner: "Corporate cards, expense management, and procurement platform.",
    authMethods: ["OAuth2"], selfServe: "Partial",
    selfServeNote: "Ramp account required (US businesses); developer sandbox on request",
    apiSurface: "REST", apiBreath: "Wide(50+)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.ramp.com/developer-guide/",
    buildabilityBlocker: "",
  },
  {
    id: 90, appName: "PitchBook",
    oneLiner: "Private market financial data and research platform for VC/PE professionals.",
    authMethods: ["API Key"], selfServe: "No",
    selfServeNote: "Enterprise subscription required; API access gated by sales",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.pitchbook.com",
    buildabilityBlocker: "Enterprise/sales-gated; expensive data license; not in Composio",
  },

  // ── 10. AI, Research and Media-native ────────────────────────────────────
  {
    id: 91, appName: "NotebookLM",
    oneLiner: "Google's AI research assistant for document analysis and note synthesis.",
    authMethods: ["No Auth (via Gemini API)"], selfServe: "Yes",
    selfServeNote: "Gemini API free tier; API key from Google AI Studio",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    buildabilityBlocker: "NotebookLM itself has no public API; Gemini API ≠ NotebookLM",
  },
  {
    id: 92, appName: "Otter AI",
    oneLiner: "AI meeting transcription and note-taking assistant.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan; official MCP server documented at otter.ai",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: true, mcpNote: "Official Otter.ai MCP server published",
    docsUrl: "https://help.otter.ai/hc/en-us/articles/mcp",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 93, appName: "Fathom",
    oneLiner: "AI meeting recorder and summarizer with CRM sync.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Free plan available; OAuth for third-party integrations",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://fathom.video/developers",
    buildabilityBlocker: "Only 7 tools in Composio; limited API surface",
  },
  {
    id: 94, appName: "Consensus",
    oneLiner: "AI-powered scientific literature search and evidence synthesis engine.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Partial",
    selfServeNote: "Free tier for manual use; API access requires application/waitlist",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://consensus.app/home/blog/consensus-api/",
    buildabilityBlocker: "API in limited beta; not in Composio",
  },
  {
    id: 95, appName: "Reducto",
    oneLiner: "Document parsing and extraction API with high-fidelity layout understanding.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Free credits on signup; API key from reducto.ai dashboard",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://docs.reducto.ai",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 96, appName: "Devin",
    oneLiner: "Autonomous AI software engineer by Cognition with API and MCP integration.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "Devin API access at docs.devin.ai; MCP server available",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: true, mcpNote: "Official Devin MCP server (devin_mcp) — in Composio registry",
    docsUrl: "https://docs.devin.ai",
    buildabilityBlocker: "",
  },
  {
    id: 97, appName: "higgsfield",
    oneLiner: "AI video generation platform with character consistency and cinematic tools.",
    authMethods: ["API Key"], selfServe: "Yes",
    selfServeNote: "API access available via higgsfield.ai; CLI and API key",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://higgsfield.ai/docs",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
  {
    id: 98, appName: "Mermaid CLI",
    oneLiner: "Open-source tool for generating diagrams from Markdown-like text syntax.",
    authMethods: ["None"], selfServe: "Yes",
    selfServeNote: "MIT-licensed OSS; no API — runs locally via Node.js CLI",
    apiSurface: "No public API", apiBreath: "None",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://github.com/mermaid-js/mermaid-cli",
    buildabilityBlocker: "CLI/library only — no REST API; agent toolkit needs custom wrapper",
  },
  {
    id: 99, appName: "YouTube Transcript",
    oneLiner: "Third-party API service for fetching YouTube video transcripts.",
    authMethods: ["OAuth2"], selfServe: "Yes",
    selfServeNote: "Uses YouTube Data API v3; free quota via Google Cloud Console",
    apiSurface: "REST", apiBreath: "Medium(10-50)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://developers.google.com/youtube/v3",
    buildabilityBlocker: "",
  },
  {
    id: 100, appName: "Grain",
    oneLiner: "AI meeting intelligence platform with recording, highlights, and CRM sync.",
    authMethods: ["OAuth2", "API Key"], selfServe: "Yes",
    selfServeNote: "Free plan available; API access via developer settings",
    apiSurface: "REST", apiBreath: "Narrow(<10)",
    hasMCP: false, mcpNote: "",
    docsUrl: "https://grain.com/developers",
    buildabilityBlocker: "Not in Composio toolkit registry",
  },
];
